# Generated by Django 5.2.7 on 2025-10-20 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_pritem_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pritem',
            old_name='estimated_unit_cost',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='pritem',
            name='stock_no',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='fund_cluster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='responsibility_center_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pritem',
            name='unit',
            field=models.CharField(choices=[('amp', 'Ampere'), ('bag', 'Bag'), ('bar', 'Bar'), ('batch', 'Batch'), ('block', 'Block'), ('board', 'Board'), ('book', 'Book'), ('bottle', 'Bottle'), ('box', 'Box'), ('bundle', 'Bundle'), ('bunch', 'Bunch'), ('can', 'Can'), ('carton', 'Carton'), ('case', 'Case'), ('cm', 'Centimeter'), ('cuft', 'Cubic Foot'), ('cum', 'Cubic Meter'), ('cup', 'Cup'), ('day', 'Day'), ('dozen', 'Dozen'), ('drum', 'Drum'), ('each', 'Each'), ('envelope', 'Envelope'), ('ft', 'Foot'), ('gal', 'Gallon'), ('g', 'Gram'), ('hour', 'Hour'), ('in', 'Inch'), ('jar', 'Jar'), ('job', 'Job'), ('jug', 'Jug'), ('kg', 'Kilogram'), ('km', 'Kilometer'), ('length', 'Length'), ('liter', 'Liter'), ('lot', 'Lot'), ('m', 'Meter'), ('mg', 'Milligram'), ('ml', 'Milliliter'), ('mm', 'Millimeter'), ('month', 'Month'), ('pad', 'Pad'), ('pail', 'Pail'), ('pair', 'Pair'), ('pack', 'Pack'), ('packet', 'Packet'), ('panel', 'Panel'), ('pc', 'Piece'), ('plate', 'Plate'), ('pot', 'Pot'), ('pouch', 'Pouch'), ('quart', 'Quart'), ('ream', 'Ream'), ('roll', 'Roll'), ('sack', 'Sack'), ('sachet', 'Sachet'), ('set', 'Set'), ('sheet', 'Sheet'), ('sqft', 'Square Foot'), ('sqm', 'Square Meter'), ('stick', 'Stick'), ('strip', 'Strip'), ('tank', 'Tank'), ('tray', 'Tray'), ('tube', 'Tube'), ('unit', 'Unit'), ('volt', 'Volt'), ('watt', 'Watt'), ('yard', 'Yard'), ('year', 'Year'), ('others', 'Others (Specify)')], max_length=20),
        ),
    ]
