# Generated by Django 5.2.7 on 2025-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_estimated_unit_cost_pritem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pritem',
            name='estimated_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
