# Generated by Django 5.2.7 on 2025-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_pritem_estimated_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pritem',
            name='estimated_total_cost',
        ),
        migrations.AddField(
            model_name='pritem',
            name='stock_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
