# Generated by Django 5.2.7 on 2025-10-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_pritem_estimated_total_cost_pritem_stock_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='date',
            new_name='pr_date',
        ),
    ]
