# Generated by Django 5.2.7 on 2025-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_rename_date_purchaserequest_pr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
