# Generated by Django 5.2.7 on 2025-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_pritem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('closed', 'Closed'), ('pending_supplier', 'Pending Supplier Confirmation'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
