# Generated by Django 5.2.7 on 2025-10-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_purchaserequest_last_update_purchaserequest_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='notes',
            new_name='last_note',
        ),
    ]
