# Generated by Django 5.2.7 on 2025-10-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_rename_notes_purchaserequest_last_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='last_note',
            new_name='notes',
        ),
    ]
