# Generated by Django 5.2.7 on 2025-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_rename_last_note_purchaserequest_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='fund_cluster',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requesting_office',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='responsibility_center_code',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='funding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='office_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requisitioner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
