# Generated by Django 5.2.7 on 2025-10-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_remove_purchaserequest_fund_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='funding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
