# Generated by Django 5.2.7 on 2025-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_purchaserequest_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='funding',
            field=models.CharField(blank=True, choices=[('IGF', 'Internally Generated Fund (IGF)'), ('RAF', 'Regular Agency Fund (RAF)'), ('TRF', 'Trust Receipt Fund (TRF)'), ('BRF', 'Business Related Fund (BRF)')], max_length=50, null=True),
        ),
    ]
