# Generated by Django 5.2.7 on 2025-10-25 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_alter_purchaserequest_funding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='funding',
            field=models.CharField(blank=True, choices=[('IGF', 'Internally Generated Fund (IGF)'), ('RAF', 'Regular Agency Fund (RAF)'), ('TRF', 'Trust Receipt Fund (TRF)'), ('BRF', 'Business Related Fund (BRF)')], help_text='Select the fund source', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
