# Generated by Django 5.2.7 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_remove_purchaserequest_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Verification'), ('verified', 'Verified'), ('endorsed', 'Endorsed for Approval'), ('approved', 'Approved'), ('for_rfq', 'For RFQ Preparation'), ('rfq_created', 'RFQ Created'), ('rfq_closed', 'RFQ Closed'), ('for_aoq', 'For AOQ Preparation'), ('aoq_approved', 'AOQ Approved'), ('for_po', 'For PO Preparation'), ('po_issued', 'PO Issued'), ('delivered', 'Items Delivered'), ('inspected', 'Inspected'), ('closed', 'Closed'), ('for_pb', 'For Public Bidding'), ('pre_bid', 'Pre-Bid Conference'), ('bidding_open', 'Bidding Open'), ('bid_evaluation', 'Bid Evaluation'), ('post_qualification', 'Post-Qualification'), ('bac_resolution', 'BAC Resolution Issued'), ('notice_of_award', 'Notice of Award Issued'), ('contract_preparation', 'Contract Preparation'), ('contract_signed', 'Contract Signed'), ('notice_to_proceed', 'Notice to Proceed Issued'), ('delivery_completed', 'Delivery Completed'), ('payment_processing', 'Payment Processing'), ('cancelled', 'Cancelled'), ('failed_bidding', 'Failed Bidding'), ('disqualified', 'Disqualified Bidder')], default='draft', max_length=20),
        ),
    ]
