# Generated by Django 5.2.7 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='mode_of_procurement',
            field=models.CharField(blank=True, choices=[('Competitive Bidding', 'Competitive Bidding'), ('Limited Source Bidding', 'Limited Source Bidding'), ('Competitive Dialogue', 'Competitive Dialogue'), ('Unsolicited Offer with Bid Matching', 'Unsolicited Offer with Bid Matching'), ('Direct Contracting', 'Direct Contracting'), ('Direct Acquisition', 'Direct Acquisition'), ('Repeat Order', 'Repeat Order'), ('Small Value Procurement', 'Small Value Procurement'), ('Negotiated Procurement', 'Negotiated Procurement'), ('Direct Sales', 'Direct Sales'), ('Direct Procurement for Science, Technology and Innovation', 'Direct Procurement for Science, Technology and Innovation')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='negotiated_type',
            field=models.CharField(blank=True, choices=[('Two Failed Biddings', 'Two Failed Biddings'), ('Emergency Cases', 'Emergency Cases'), ('Take-over of Contracts', 'Take-over of Contracts'), ('Adjacent or Contiguous', 'Adjacent or Contiguous'), ('Agency-to-Agency', 'Agency-to-Agency'), ('Scientific, Scholarly or Artistic Work, Exclusive Technology and Media Services', 'Scientific, Scholarly or Artistic Work, Exclusive Technology and Media Services'), ('Highly Technical Consultants', 'Highly Technical Consultants'), ('Defense Cooperation Agreements and Inventory-Based Items', 'Defense Cooperation Agreements and Inventory-Based Items'), ('Lease of Real Property and Venue', 'Lease of Real Property and Venue'), ('Non-Government Organization (NGO) Participation', 'Non-Government Organization (NGO) Participation'), ('Community Participation', 'Community Participation'), ('United Nations (UN) Agencies, International Organizations or International Financing Institutions', 'United Nations (UN) Agencies, International Organizations or International Financing Institutions'), ('Direct Retail Purchase of Petroleum Fuel, Oil and Lubricant Products, Electronic Charging Devices, and Online Subscriptions', 'Direct Retail Purchase of Petroleum Fuel, Oil and Lubricant Products, Electronic Charging Devices, and Online Subscriptions')], help_text="If 'Negotiated Procurement' is selected, specify the type here.", max_length=200, null=True),
        ),
    ]
