# Generated by Django 5.2.7 on 2025-10-30 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_signatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_number',
            field=models.CharField(blank=True, help_text='Format: MM-NNNN-YY Short text (e.g., 10-0042-25 Printer Request)', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='PR number must follow the format: MM-NNNN-YY Short text (e.g., 10-0042-25 Printer Request).', regex='^\\d{2}-\\d{4}-\\d{2}\\s.+$')]),
        ),
    ]
