# Generated by Django 5.2.7 on 2025-10-30 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_alter_purchaserequest_pr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_number',
            field=models.CharField(blank=True, help_text='Format: 10-0042-25 Requesting Office)', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='PR number must follow the format: (10-0042-25 Requesting Office).', regex='^\\d{2}-\\d{4}-\\d{2}\\s.+$')]),
        ),
    ]
