# Generated by Django 5.2.7 on 2025-11-01 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_alter_bid_options_bid_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractofquotation',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractofquotation',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aoqs_awarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractofquotation',
            name='awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_aoqs', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='resolution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='resolution_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_resolutions_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
