# Generated by Django 5.2.7 on 2025-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_abstractofquotation_awarded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractofquotation',
            name='computed_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pritem',
            name='budget_category',
            field=models.CharField(choices=[('PS', 'Personal Services'), ('MOOE', 'Maintenance & Other Operating Expenses'), ('CO', 'Capital Outlay'), ('OTHER', 'Other')], default='MOOE', max_length=20),
        ),
    ]
