# Generated by Django 5.2.7 on 2025-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_abstractofquotation_computed_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidline',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
