# Generated by Django 5.2.7 on 2025-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_bidline_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidline',
            name='offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
