# Generated by Django 5.2.7 on 2025-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_alter_bidline_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
