# Generated by Django 5.2.7 on 2025-11-06 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0028_alter_bidline_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='consolidated_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_prs', to='procurement.requestforquotation'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='consolidated_prs',
            field=models.ManyToManyField(blank=True, related_name='rfqs', to='procurement.purchaserequest'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='purchase_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq', to='procurement.purchaserequest'),
        ),
    ]
