# Generated by Django 5.2.7 on 2025-11-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0029_purchaserequest_consolidated_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQConsolidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consolidated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consolidated_prs', models.ManyToManyField(related_name='consolidation_logs', to='procurement.purchaserequest')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_logs', to='procurement.requestforquotation')),
            ],
        ),
    ]
