# Generated by Django 5.2.7 on 2025-11-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_rfqconsolidationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforquotation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='updated_by',
        ),
    ]
