# Generated by Django 5.2.7 on 2025-11-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0033_alter_pritem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='attachments',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
